### ISSUE TITLE
newDate doesn't calculate the date correctly

### ISSUE THREAD

**Issue by ali-garajian** [date-fns-jalali/date-fns-jalali#57]
Either I'm missing something obvious here, or this is indeed a bug! 
I'm trying to use the `newDate` function to convert a jalali date to a `Date` object and pass it to the `format` function for further processing. The problem is that the dates don't match!
I'm not sure if this is the root cause of the problem, but I think the newDate function isn't calculating the Date object correctly. 
Even the results in the examples you've provided for this function aren't correct!

```
format(newDate(1392, 10, 22), 'yyyy MMMM d')
// 1392 بهمن 22 <-- shouldn't this be : 1392 22 دی since the 10th month would be دی not بهمن
```

I'm using it like this : 
`format(newDate(1392, 10, 22), 'P')`
and this results in 
`1392/11/22`

Any help would be much appreciated

**Comment by smmoosavi** [comment]
It's correct. the `newDate` tries to look like the `new Date` function of javascript. javascript `new Date` get month index:


> ### monthIndex
> Integer value representing the month, beginning with 0 for January to 11 for December

same as `new Date` the `newDate` functions month arguments is an integer value representing the month, beginning with 0 for Farvadin to 11 for Esfand.

**Comment by ali-garajian** [comment]
You're right! 
It's confusing how the day parameter is not zero-indexed though! Looks like an old quirk from Java!
Thank a lot :)
