### ISSUE TITLE
wrong date calculation

### ISSUE THREAD

**Issue by javadbat** [date-fns-jalali/date-fns-jalali#60]
![image](https://user-images.githubusercontent.com/11534875/135848229-4b8b46f1-7168-41e6-b110-c3c56d03884a.png)
![image](https://user-images.githubusercontent.com/11534875/135848344-5f66ba89-dfc5-4f90-8401-e0bbf3046273.png)
:|
i just want to get first day of year and it returns wrong date

**Comment by javadbat** [comment]
![image](https://user-images.githubusercontent.com/11534875/135850414-9b0605fd-14ae-4be7-8b93-8cbd6bd3a9a7.png)

**Comment by smmoosavi** [comment]
Same as #57. see this [comment]

[comment]: https://github.com/date-fns-jalali/date-fns-jalali/issues/57#issuecomment-912950588

**Comment by Sinakhx** [comment]
@smmoosavi 
as I see the main issue here is not with knowing the zero-index convention, but with the `toISOString()` method which returns wrong results.

**Comment by Sinakhx** [comment]
> Same as #57. see this [comment](https://github.com/date-fns-jalali/date-fns-jalali/issues/57#issuecomment-912950588)
@smmoosavi
as I see the main issue here is not with overlooking the zero-index convention, but with the toISOString() method chained to newDate which returns wrong results.

**Comment by Sinakhx** [comment]
@javadbat 

here seems to be the correct usage for converting to `ISOString`:

```js
import { newDate, formatISO } from "date-fns-jalali"

const date = newDate(1400, 0, 1);
const iso = formatISO(date);
console.log(iso); //-> "2021-03-21T00:00:00+03:30"
````
