### ISSUE TITLE
inconsistent results with Intl.DateTimeFormat

### ISSUE THREAD

**Issue by Sinakhx** [date-fns-jalali/date-fns-jalali#62]
## The problem
for the particular **Gregorian** date of `2256-03-20`, the results are not consistent with the JavaScript's built-in `Intl.DateTimeFormat` API. I'm not sure which result is true: `1634/12/30` or `1635/01/01` with one day offset.
the problem might stem from jalali leap year (or even midnight) calculation differences which I don't know about.

### 💻 Code demonstrating the problem

```js
import { format } from 'date-fns-jalali';

const intlDate = new Date('2256-03-20').toLocaleDateString('fa-IR');    // -> 1634/12/30
const fnsDate = format(new Date('2256-03-20'), 'yyyy/MM/dd');           // -> 1635/01/01

console.log({ IntlDate, fnsDate }); // -> {intlDate: "۱۶۳۴/۱۲/۳۰", fnsDate: "1635/01/01"}
```

#### online playground
codesandbox: https://codesandbox.io/s/date-fns-jalali-vs-intl-datetimeformat-zd0q9p?file=/src/index.ts
runkit: https://runkit.com/sinakhx/626790d31a0e790008447d10

### 🙁 Actual behavior

I was hoping both the date-fns & Intl results to be the same. (either 1634/12/30 or 1635/01/01)

### 🙂 Expected behavior

I'm not sure which result is correct (the date-fns result or the built-in result). I've also checked it against the `time.ir` website which approves the date-fns results but how on Earth can built-in results be falsy?
If the built-in method is going wrong, then how can I report that bug?

## Debug information

- date-fns-jalali version: 2.28.0
- Browser/Node.js version: node v16.14.1 & Chrome v100.0.4896.75 (Official Build) (64-bit)
- Your timezone: Asia/Tehran
- Your current time: 01:25

**Comment by smmoosavi** [comment]
Thank you for reporting the issue.

I will investigate the issue soon.

**Comment by smmoosavi** [comment]
# Nodejs

node.js uses the simple rule (33-year rule) for leap years, which is correct between 1210 and 1635:

```cpp
UBool PersianCalendar::isLeapYear(int32_t year)
{
    int32_t remainder;
    ClockMath::floorDivide(25 * year + 11, 33, remainder);
    return (remainder < 8);
}
```

[source](https://github.com/nodejs/node/blob/6c86af9faa72ef68a728282a56f5d95d93ab3144/deps/icu-small/source/i18n/persncal.cpp#L110)

# date-fns-jalali

date-fns-jalali use the 33-year rule and pre-calculated break [years], which 33-year not working.


# Other methods

I found another [method][akrami-method] for leap year «گاهشماری حسابی رایانه‌ای» which has better performance. Maybe in future date-fns-jalali use that method

[akrami-method]: https://fa.wikipedia.org/wiki/%DA%AF%D8%A7%D9%87%E2%80%8C%D8%B4%D9%85%D8%A7%D8%B1%DB%8C_%D9%87%D8%AC%D8%B1%DB%8C_%D8%AE%D9%88%D8%B1%D8%B4%DB%8C%D8%AF%DB%8C_%D8%AD%D8%B3%D8%A7%D8%A8%DB%8C
[years]: https://github.com/date-fns-jalali/date-fns-jalali/blob/e42d54e0237d8d1e4ada53be5083a6c30a7941c5/src/_jalali/index.ts#L5

**Comment by Sinakhx** [comment]
Thanks for your investigation & response. It sounds like there is no universal standard convention for calculating jalali leap years, so that even the `Intl` API goes for a simplistic approach; However, the [other method](https://fa.wikipedia.org/wiki/%DA%AF%D8%A7%D9%87%E2%80%8C%D8%B4%D9%85%D8%A7%D8%B1%DB%8C_%D9%87%D8%AC%D8%B1%DB%8C_%D8%AE%D9%88%D8%B1%D8%B4%DB%8C%D8%AF%DB%8C_%D8%AD%D8%B3%D8%A7%D8%A8%DB%8C) that you've noticed seems to be more accurate. I hope the `Intl` work-group switch to the same approach in the near future.

**Comment by Sinakhx** [comment]
> I found another [method](https://fa.wikipedia.org/wiki/%DA%AF%D8%A7%D9%87%E2%80%8C%D8%B4%D9%85%D8%A7%D8%B1%DB%8C_%D9%87%D8%AC%D8%B1%DB%8C_%D8%AE%D9%88%D8%B1%D8%B4%DB%8C%D8%AF%DB%8C_%D8%AD%D8%B3%D8%A7%D8%A8%DB%8C) for leap year «گاهشماری حسابی رایانه‌ای» which has better performance. Maybe in future date-fns-jalali use that method

I've found out that the `Intl.DateTimeFormat` API is not going the wrong way. The bug is actually here.
Maybe it's a better idea to not jump into implementation based on Wikipedia's content.

Here you can see why: https://github.com/unicode-org/icu/pull/2077#issuecomment-1127190385

**Comment by smmoosavi** [comment]
`date-fns-jalali@v3` uses the same algorithm as Intl.

v2 and v3 algorithm are the same between 1178 and 1633.
