### ISSUE TITLE
Error in interface CurriedFn1<A, R>

### ISSUE THREAD

**Issue by reza1984** [date-fns-jalali/date-fns-jalali#64]
### 💻 Code demonstrating the problem
After upgrading node and angular to v14 when I build my angular app I get these errors

<img width="1307" alt="Screen Shot 2022-06-09 at 7 21 22 PM" src="https://user-images.githubusercontent.com/12760842/172879394-df693db2-0b2f-4376-a96f-16191ea6c0dd.png">

- date-fns-jalali version: 2.28.0-0
- Node.js version: v14.19.3
- Your timezone: Asia/Tehran

**Comment by smmoosavi** [comment]
Thanks for reporting the issue, I can reproduce the problem, and I will fix it soon

**Comment by smmoosavi** [comment]
Please check `v2.28.0-1`. It should fix the problem.
