### ISSUE TITLE
use this package for UMD build 

### ISSUE THREAD

**Issue by javadbat** [date-fns-jalali/date-fns-jalali#65]
## The problem
I want to import date-fns-jalali in the script tag in my non-npm package
### 💻 Code demonstrating the problem
```html
<head>
  <script src="https://unpkg.com/date-fns-jalali">
    dateFnsJalali.fn();
  </script>
</head>
```

### 🙁 Actual behavior

there is no documentation about how I can use this package in UMD.
I develop `jb-date-input` package in npm that use `date-fns-jalali` as a date engine and I want to publish my web-component in UMD so everyone can use web-component without npm in their static site so I need a global name of your date package to config my build file so I can publish `umd` package

### 🙂 Expected behavior

 add umd package so we can import your files from cdn with script tag

**Comment by smmoosavi** [comment]
Sorry for the late response.

As I know, `date-fns` doesn't provide UMD build. date-fns have 200+ functions, and most libs only use just a few numbers of these functions (jb-date-input use less than ten functions). UMD build is not tree-shakeable and will have a huge size.

date-fns-jalali uses the same build script as date-fns and doesn't create UMD

## Solution

If you insist on building UMD, you can embed date-fns-jalali functions. e.g., if you are using rollup, you can remove date-fns from the external option

**Comment by javadbat** [comment]
thank you morteza
yes, you are right. actually, I do exactly what you say and include these file into UMD build and everything works perfectly
thank you for your time
