### ISSUE TITLE
Missing export for longFormatters methods from lib/formats [v.3.6.0-0]

### ISSUE THREAD

**Issue by amirhsobhi** [date-fns-jalali/date-fns-jalali#66]
I was trying to use the library as an adapter for the MUI/x-date-pickers
this issue shows up: 
`ERROR in ./node_modules/@mui/x-date-pickers/AdapterDateFnsJalali/AdapterDateFnsJalali.js 59:0-72
Module not found: Error: Package path ./_lib/format/longFormatters is not exported from package /Users/myuser/newproj/fe-ts/node_modules/date-fns-jalali (see exports field in /Users/myuser/newproj/fe-ts/node_modules/date-fns-jalali/package.json)`

it seems the longFormatters is not exported from the index file.

<img width="464" alt="Screenshot 2024-04-21 at 11 38 30 at night" src="https://github.com/date-fns-jalali/date-fns-jalali/assets/35629279/6910919a-5f79-47e3-a241-3b1b9393d86c">
<img width="530" alt="Screenshot 2024-04-21 at 11 37 58 at night" src="https://github.com/date-fns-jalali/date-fns-jalali/assets/35629279/43fdd5ab-ca1c-4156-a46d-bb5d4f6e1989">

**Comment by smmoosavi** [comment]
The `@mui/x-date-pickers` have multiple date-fns, date-fns-jalali adapter. Right now `@mui/x-date-pickers` only support date-fns-jalali@v2

I will try to add `AdapterDateFnsJalaliV3` to `@mui/x-date-pickers` soon

| date-fns | @mui/x-date-pickers |
|--------|--------|
| `date-fns@v2` | `AdapterDateFns` |
| `date-fns@v3` | `AdapterDateFnsV3` |
| `date-fns-jalali@v2` | `AdapterDateFnsJalali` |
| `date-fns-jalali@v3` |  |

**Comment by smmoosavi** [comment]
AdapterDateFnsJalaliV3 pull request is ready https://github.com/mui/mui-x/pull/12891

**Comment by smmoosavi** [comment]
https://github.com/mui/mui-x/releases/tag/v7.4.0

**Comment by smortexa** [comment]
This error also exists in the latest version of this package when used with the `@date-io/date-fns-jalali` library. Downgrading to version `2.30.0-0` resolves this issue:
```json
// package.json
{
  "dependencies": {
		"@date-io/date-fns-jalali": "^3.0.0",
		"date-fns-jalali": "^3.6.0-1",
	}
}
```
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/269f80b5-370f-4570-bf30-39d61b1989b7">

**Comment by smmoosavi** [comment]
Thanks for reporting the issue

https://github.com/dmtrKovalenko/date-io/pull/669
