### ISSUE TITLE
Bug found in the 'addMonths' function

### ISSUE THREAD

**Issue by Abbasr7** [date-fns-jalali/date-fns-jalali#68]
## The problem
hi, thank you for great package.
In leap years, the addMonth function does not work correctly in the months of January and February, for example:
If you addmonth 1 for the date 30 Mehr 1403, it will be 1 Azr 1403, or from 30 Azr it will be 1 Bahman

### 💻 Code demonstrating the problem

![image](https://github.com/user-attachments/assets/c85991fe-90e3-48bc-a6a9-89b96a63ce45)

![image](https://github.com/user-attachments/assets/8301ef63-bc97-4473-b011-dc0b0b1e5336)

![image](https://github.com/user-attachments/assets/c6c0bd42-66e2-4941-9026-da90d00c7d02)

- date-fns-jalali version: [4.1.0-0]

**Comment by smmoosavi** [comment]
Thanks for reporting the issue. I wrote a date-fns-jalali example and it works correctly.

```js
const { newDate, format, addMonths } = require("date-fns-jalali");

let d1 = newDate(1403,6, 30);
console.log(format(d1, "yyyy/MMMM/dd")); // 1403/مهر/30
let d2 = addMonths(d1, 1);
console.log(format(d2, "yyyy/MMMM/dd")); // 1403/آبان/30


let d3 = newDate(1403,8, 30);
console.log(format(d3, "yyyy/MMMM/dd")); // 1403/آذر/30
let d4 = addMonths(d3, 1);
console.log(format(d4, "yyyy/MMMM/dd")); // 1403/دی/30
```
